### ISSUE TITLE
Fixes: Navbar Can Be Fixed(Style)

### ISSUE THREAD

**Issue by Lakszy** [MrMaina100/Movie-Verse#3]
**To** **Produce**: On the Landing Page.
We can give the navbar section full-width 

![image](https://github.com/MrMaina100/Movie-Verse/assets/117038630/8312793b-5a92-44b5-87d6-b6b49b7339e8)

With Some Fixes This is how the Navbar will look
![image](https://github.com/MrMaina100/Movie-Verse/assets/117038630/ab0da496-9e05-44cc-a2f2-f2a943299265)

**Comment by MrMaina100** [comment]
hey @Lakszy will definitely fix that. Thanks
