### ISSUE TITLE
Fixes: Details On The Movie Page Can Be Fixed

### ISSUE THREAD

**Issue by Lakszy** [MrMaina100/Movie-Verse#4]
To Produce: On The Landing Page Simply Click On Any Of The Movie.

**The details and the description don't look up to the mark** 

![image](https://github.com/MrMaina100/Movie-Verse/assets/117038630/7aac5f57-ea9f-430b-a6c5-7664732a24cd)

**With Some Fixes**

![image](https://github.com/MrMaina100/Movie-Verse/assets/117038630/60313f1a-13d6-45ab-af93-e86769cf3139)

**Comment by MrMaina100** [comment]
hey @Lakszy hehe this was actually my first  project in react ...might be a bit blunt and salty but am working on something new

**Comment by Lakszy** [comment]
Hello @MrMaina100, you're doing great on your first project! PS. This was my first React project as well. Good luck with what lies ahead!
